spring:
  profiles:
    #名称和pom文件定义的标签一致;主要利用了maven打包时，拦截配置文件使用pom文件中的值替换掉spring.profiles.active=@activatedProperties@中的变量，完成动态配置文件的使用功能。
    active: @activatedProperties@
  #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404,和add-mappings: false配合使用)
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.jonlin.model  # 注意：对应实体类的路径

